// Generates Unity's emoji alias table from the canonical BCChat C++ table.
// Usage: node tools/generateEmojiShortcodes.js
const fs = require("fs");
const path = require("path");

const projectRoot = path.join(__dirname, "..");
const cppTablePath = path.join(projectRoot, "..", "..", "cpp-examples", "bcchat", "src", "emojiShortcodes.generated.h");
const outputPath = path.join(projectRoot, "Assets", "App", "Scripts", "UI", "EmojiShortcodes.generated.cs");
const input = fs.readFileSync(cppTablePath, "utf8");
const entries = [];
const row = /\{\s*"([^"]+)"\s*,\s*"((?:\\x[0-9A-Fa-f]{2})+)"\s*\}/g;

for (let match; (match = row.exec(input));) {
    const bytes = [...match[2].matchAll(/\\x([0-9A-Fa-f]{2})/g)].map(value => parseInt(value[1], 16));
    const emoji = Buffer.from(bytes).toString("utf8");
    const escapedEmoji = [...emoji]
        .map(character => {
            const codepoint = character.codePointAt(0);
            if (codepoint <= 0xFFFF) return `\\u${codepoint.toString(16).padStart(4, "0").toUpperCase()}`;
            const value = codepoint - 0x10000;
            const high = 0xD800 + (value >> 10);
            const low = 0xDC00 + (value & 0x3FF);
            return `\\u${high.toString(16).toUpperCase()}\\u${low.toString(16).toUpperCase()}`;
        })
        .join("");
    entries.push(`        { "${match[1]}", "${escapedEmoji}" },`);
}

if (entries.length === 0) throw new Error(`No emoji entries found in ${cppTablePath}`);

const output = `// Generated by tools/generateEmojiShortcodes.js; do not edit by hand.
// Data source: github/gemoji (MIT License), via the BCChat C++ generated table.
using System;
using System.Collections.Generic;

public static partial class EmojiShortcodes
{
    private static readonly Dictionary<string, string> Aliases = new(StringComparer.Ordinal)
    {
${entries.join("\n")}
    };
}
`;

fs.writeFileSync(outputPath, output);
console.log(`Generated ${entries.length} Unity emoji aliases in ${outputPath}`);
